server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  config:
    import: optional:configserver:http://localhost:9296
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka