server:
  port: 8070
spring:
  application:
    name: assurance
  zipkin:
    base-url: http://127.0.0.1:9411/
  config:
    import: optional:configserver:http://localhost:9296
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true

application:
  config:
    assurancePolicy-url: http://192.168.49.2:30950/api/v1/assurancePolicy

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0